db.url=jdbc:sqlserver://localhost:1433;databaseName=SmartNewsDB;encrypt=true;trustServerCertificate=true
db.user=doctormine
db.password=Truong123@@
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=9999
